version: "3.9"
services:
  postgres:
    image: postgres
    container_name: FrontToBack
    env_file:
      - path: ../.env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
